#
# !!!  NOT WORKING DUE TO REQUIRED LINUX KERNEL SRC FOR PARSING  !!!
#

name: CI Pipeline [Ubuntu]

on: [push, pull_request]

env:
  PROJECT_BUILD_TYPE: Release
  PROJECT_BASE_PATH: '${{github.workspace}}'
  PROJECT_BUILD_PATH: '${{github.workspace}}/build'

jobs:
  ministrace:
    name: Build ministrace
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
         # Required --> doesn't work ?
#        with:
#          submodules: recursive
      # >> WORKAROUND <<
      - name: Checkout submodules
        shell: bash
        run: |
          cd $PROJECT_BASE_PATH
          git rm --cached ext/atomic_hash
          rm -rf ext/atomic_hash
          git submodule add --force https://github.com/therealthingy/atomic_hash.git ext/atomic_hash


      # - Clean (unnecessary ??) + Build -
      - name: Cleanup
        shell: bash
        run: rm -rf $PROJECT_BUILD_PATH

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory $PROJECT_BUILD_PATH

      - name: Configure CMake
        shell: bash
        run: cmake -B $PROJECT_BUILD_PATH -S $PROJECT_BASE_PATH -DCMAKE_BUILD_TYPE=$PROJECT_BUILD_TYPE

      - name: Build w/ CMake
        shell: bash
        run: cmake --build $PROJECT_BUILD_PATH --config $PROJECT_BUILD_TYPE
